import { bitcoin, mainnet, solana, ton } from "@reown/appkit/networks";
import type {
  AppKitNetworkConfig,
  ChainFamily,
  ChainId,
  NetworkDefinition,
} from "./types";

export const POLKADOT_NETWORK: AppKitNetworkConfig = {
  id: "91b171bb158e2d3848fa23a9f1c25182",
  name: "Polkadot",
  nativeCurrency: {
    name: "Polkadot",
    symbol: "DOT",
    decimals: 10,
  },
  rpcUrls: {
    default: {
      http: ["https://rpc.polkadot.io"],
    },
  },
  blockExplorers: {
    default: {
      name: "Subscan",
      url: "https://polkadot.subscan.io",
    },
  },
  chainNamespace: "polkadot",
  caipNetworkId: "polkadot:91b171bb158e2d3848fa23a9f1c25182",
  testnet: false,
};

export const NETWORKS: Record<ChainId, NetworkDefinition> = {
  evm: {
    id: "evm",
    family: "evm",
    namespace: "eip155",
    label: "EVM",
    badge: "EVM",
    explorerUrl: "https://etherscan.io/address/",
    explorerLabel: "Explorer",
    appKitNetwork: mainnet,
    alphabet: "hex",
    searchTarget: "full-address",
    placeholderPrefix: "c0de",
    placeholderSuffix: "beef",
    prefixHint: "Hex prefix without 0x",
    suffixHint: "Hex suffix without 0x",
    secretFormat: "hex-private-key",
    supportsChecksum: true,
    supportsBitcoinAddressType: false,
    defaultBatchSize: 512,
  },
  solana: {
    id: "solana",
    family: "solana",
    namespace: "solana",
    label: "Solana",
    badge: "SOL",
    explorerUrl: "https://solscan.io/account/",
    explorerLabel: "Solscan",
    appKitNetwork: solana,
    alphabet: "base58",
    searchTarget: "full-address",
    placeholderPrefix: "sun",
    placeholderSuffix: "pump",
    prefixHint: "Base58 prefix",
    suffixHint: "Base58 suffix",
    secretFormat: "base58-secret-key",
    supportsChecksum: false,
    supportsBitcoinAddressType: false,
    defaultBatchSize: 384,
  },
  bitcoin: {
    id: "bitcoin",
    family: "bitcoin",
    namespace: "bip122",
    label: "Bitcoin",
    badge: "BTC",
    explorerUrl: "https://mempool.space/address/",
    explorerLabel: "Mempool",
    appKitNetwork: bitcoin,
    alphabet: "bech32-body",
    searchTarget: "body-after-prefix",
    fixedPrefix: "bc1p",
    placeholderPrefix: "sats",
    placeholderSuffix: "moon",
    prefixHint: "Body after bc1p / bc1q",
    suffixHint: "Body after bc1p / bc1q",
    secretFormat: "wif",
    supportsChecksum: false,
    supportsBitcoinAddressType: true,
    defaultBatchSize: 256,
  },
  ton: {
    id: "ton",
    family: "ton",
    namespace: "ton",
    label: "TON",
    badge: "TON",
    explorerUrl: "https://tonscan.org/address/",
    explorerLabel: "TON Scan",
    appKitNetwork: ton,
    alphabet: "base64url",
    searchTarget: "body-after-prefix",
    fixedPrefix: "EQ",
    placeholderPrefix: "ton",
    placeholderSuffix: "moon",
    prefixHint: "Body after EQ",
    suffixHint: "Body after EQ",
    secretFormat: "hex-seed",
    supportsChecksum: false,
    supportsBitcoinAddressType: false,
    defaultBatchSize: 384,
  },
  polkadot: {
    id: "polkadot",
    family: "substrate",
    namespace: "polkadot",
    label: "Polkadot",
    badge: "DOT",
    explorerUrl: "https://polkadot.subscan.io/account/",
    explorerLabel: "Subscan",
    appKitNetwork: POLKADOT_NETWORK,
    alphabet: "base58",
    searchTarget: "full-address",
    placeholderPrefix: "west",
    placeholderSuffix: "seed",
    prefixHint: "SS58 prefix",
    suffixHint: "SS58 suffix",
    secretFormat: "hex-seed",
    supportsChecksum: false,
    supportsBitcoinAddressType: false,
    defaultBatchSize: 320,
  },
};

export const NETWORK_LIST = Object.values(NETWORKS);

export const NETWORK_GROUPS: Record<ChainFamily, NetworkDefinition[]> = {
  evm: NETWORK_LIST.filter((network) => network.family === "evm"),
  solana: NETWORK_LIST.filter((network) => network.family === "solana"),
  bitcoin: NETWORK_LIST.filter((network) => network.family === "bitcoin"),
  ton: NETWORK_LIST.filter((network) => network.family === "ton"),
  substrate: NETWORK_LIST.filter((network) => network.family === "substrate"),
};

export function getNetworkDefinition(chainId: ChainId) {
  return NETWORKS[chainId];
}
